apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql-image
          imagePullPolicy: Never
          volumeMounts:
            - name: persistentvolume-mysql
              mountPath: var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: persistentvolume-mysql
          persistentVolumeClaim:
            claimName: persistentvolume-mysql

--- 

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentvolume-mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
