apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
         app: grafana
    spec:
      containers:
        - name: mygrafana-image
          image: grafana-image
          imagePullPolicy: Never
          ports: 
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
  type: LoadBalancer
  ports: 
  - name: grafana
    port: 3000
    targetPort: 3000
  loadBalancerIP: 192.168.99.231
  selector:
    app: grafana



