apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
     app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
         - name: myphpmyadmin-image
           image: phpmyadmin-image
           imagePullPolicy: Never
           ports:
             - containerPort: 5000

---

apiVersion: v1
kind : Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
   type: LoadBalancer
   ports:
     - name: phpmyadmin
       port: 5000
       targetPort: 5000
   loadBalancerIP: 192.168.99.231
   selector:
     app: phpmyadmin

