apiVersion: apps/v1
kind: Deployment
metadata:
   name: wordpress-deploy
   labels: 
      app: wordpress
spec:
   selector:
     matchLabels:
        app: wordpress
   replicas: 1
   strategy:
     type: Recreate
   template:
     metadata: 
       labels:
          app: wordpress
     spec: 
       containers:
          - name: mywordpress-image
            image: wordpress-image
            imagePullPolicy: Never
            ports:
             - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
     app: wordpress
  annotations:
     metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
  type: LoadBalancer
  ports:
   - name: wordpress
     port: 5050
     targetPort: 5050
  loadBalancerIP: 192.168.99.231
  selector:
    app: wordpress
