apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: myftps-container
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21000
            - containerPort: 21001
            - containerPort: 21002
            - containerPort: 21003
            - containerPort: 21004
            - containerPort: 21005

---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
   app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
   - name: ftp-connection
     port: 21
   - name: ftps-data0
     port: 21000
   - name: ftps-data1
     port: 21001
   - name: ftps-data2
     port: 21002
   - name: ftps-data3
     port: 21003
   - name: ftps-data4
     port: 21004
   - name: ftps-data5
     port: 21005
  loadBalancerIP: 192.168.99.231
